application: world-cup-bet
version: 17
runtime: python
api_version: 1

handlers:
    - url: /favicon.ico
      static_files: images/favicon.ico
      upload: images/favicon.ico
    - url: /stylesheets
      static_dir: stylesheets
    - url: /images
      static_dir: images
    - url: /lib
      static_dir: lib
    - url: /remote_api
      script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
    - url: .*
      script: main.py
